SthenosFit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from SthenosFit import settings


urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("api/v1/", include("api.urls", namespace="api")),
    path("clases/", include("clases.urls")),
    path(
        "clases_welcome/", RedirectView.as_view(url="/clases/"), name="clases_welcome"
    ),
    path("fitness/", include("fitness.urls")),
    path(
        "fitness_welcome/",
        RedirectView.as_view(url="/fitness/"),
        name="fitness_welcome",
    ),
    path("usuarios/", include("usuarios.urls")),
    path(
        "usuarios_welcome/",
        RedirectView.as_view(url="/usuarios/"),
        name="usuarios_welcome",
    ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from rest_framework import routers
from .views import ClaseViewSet, ReservaViewSet, UsuarioViewSet, ClienteViewSet

app_name = "api"
router = routers.DefaultRouter()
router.register("clases", ClaseViewSet)
router.register("reservas", ReservaViewSet)
router.register("usuarios", UsuarioViewSet)
router.register("clientes", ClienteViewSet)
urlpatterns = router.urls
# endregion

clases/urls.py
"""
URLs de la aplicación clases.
"""

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .views import (
    CrearClase,
    ListarClases,
    EditarClase,
    DetalleClase,
    EliminarClase,
    TopTenClases,
    CrearReserva,
    CrearReservaStaff,
    ListarReservas,
    EditarReserva,
    DetalleReserva,
    EliminarReserva,
    CancelarReserva,
    ListarReservasClientes,
    welcome,
)

urlpatterns = [
    # region welcome
    path("", welcome, name="welcome"),
    # region CRUD de Clases
    path(
        "nuevo/",
        staff_member_required((CrearClase.as_view())),
        name="crear_clase",
    ),
    path(
        "listado/",
        ListarClases.as_view(),
        name="listar_clases",
    ),
    path(
        "editar/<int:pk>",
        staff_member_required((EditarClase.as_view())),
        name="editar_clase",
    ),
    path(
        "eliminar/<int:pk>",
        staff_member_required((EliminarClase.as_view())),
        name="eliminar_clase",
    ),
    path(
        "detalle/<int:pk>",
        DetalleClase.as_view(),
        name="detalle_clase",
    ),
    # region Clase adicional
    path(
        "buscar_general/",
        ListarClases.as_view(),
        name="buscar_clase_general",
    ),
    path(
        "topten/",
        staff_member_required((TopTenClases.as_view())),
        name="top_ten_clases",
    ),
    # endregion
    # region CRUD de Reserva
    path(
        "reserva/nuevo/clase/<int:pk>",
        login_required(CrearReserva.as_view()),
        name="reservar_clase",
    ),
    path(
        "reserva/nuevo/clase/staff/<int:pk>",
        login_required(CrearReservaStaff.as_view()),
        name="reservar_clase_staff",
    ),
    path(
        "reserva/listado/",
        staff_member_required((ListarReservas.as_view())),
        name="listar_reservas",
    ),
    path(
        "reserva/editar/<int:pk>",
        staff_member_required((EditarReserva.as_view())),
        name="editar_reserva",
    ),
    path(
        "reserva/eliminar/<int:pk>",
        staff_member_required((EliminarReserva.as_view())),
        name="eliminar_reserva",
    ),
    path(
        "reserva/detalle/<int:pk>",
        login_required(DetalleReserva.as_view()),
        name="detalle_reserva",
    ),
    path(
        "reserva/cancelar/<int:pk>",
        login_required((CancelarReserva.as_view())),
        name="cancelar_reserva",
    ),
    # endregion
    # region Reserva
    path(
        "reserva/<str:username>/<int:pk>/listado/",
        login_required(ListarReservasClientes.as_view()),
        name="reservas_cliente",
    ),
    # endregion
]

clases/models.py
"""
Modelos de clases para la app clases del gimnasio
"""

from django.db import models


class TipoClase(models.Model):
    """
    Modelo para representar un tipo de clase.
    """

    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return str(self.nombre)


class Clase(models.Model):
    """
    Modelo para representar una clase.
    """

    tramo = models.PositiveIntegerField(
        default=20, choices=[(i, i) for i in range(20, 121, 20)]
    )
    tipo_clase = models.ForeignKey(
        TipoClase,
        on_delete=models.CASCADE,
    )
    instructor = models.ForeignKey(
        "usuarios.Usuario",
        on_delete=models.CASCADE,
        default=None,
        related_name="instructor",
    )
    cupos_disponibles = models.PositiveIntegerField(default=0)
    usuarios = models.ManyToManyField(
        "usuarios.Cliente", blank=True, related_name="usuarios"
    )
    fecha_clase = models.DateTimeField(null=True, blank=True)
    imagen = models.ImageField(upload_to="clases", blank=True, null=True)
    valido = models.BooleanField(default=True)

    def __str__(self):
        return f"Clase - {self.tipo_clase}"


class Reserva(models.Model):
    """
    Modelo para representar una reserva.
    """

    usuario = models.ForeignKey("usuarios.Usuario", on_delete=models.CASCADE)
    clase = models.ForeignKey(Clase, on_delete=models.CASCADE, null=True, blank=True)
    estado_choices = (
        ("Pendiente", "Pendiente"),
        ("Cancelada", "Cancelada"),
        ("Realizada", "Realizada"),
    )
    estado = models.CharField(
        max_length=10, choices=estado_choices, default="Pendiente"
    )
    nombre_clase = models.CharField(max_length=100, default=None)

    def __str__(self):
        return f"Reserva - {self.usuario} - {self.clase} - {self.estado}"

    def cancelar(self):
        self.estado = "Cancelada"
        self.clase.valido = False
        self.nombre_clase = self.clase.tipo_clase.nombre
        self.clase = None
        self.save()

clases/views.py
"""
Vistas de la app clases.
"""

# importa request
from django.utils import timezone
from django.http import HttpRequest, HttpResponse
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)
from django.contrib import messages
from django.urls import reverse_lazy


from .models import Clase, Reserva, TipoClase
from .forms import (
    BuscarReservaParaClientesForm,
    CrearClaseForm,
    BuscarClaseForm,
    BuscarClaseGeneralForm,
    BuscarReservaPorClienteForm,
    CrearReservaStaffForm,
)


# pylint: disable=no-member
# region welcome
def welcome(request):
    """
    Vista para la página de bienvenida.
    """
    form_general = BuscarClaseGeneralForm()
    return render(request, "clases/index.html", {"form_general": form_general})


# endregion


# region CRUD de Clases
class CrearClase(CreateView):
    """
    Vista para crear una clase.
    """

    model = Clase
    success_url = reverse_lazy("listar_clases")
    form_class = CrearClaseForm


class ListarClases(ListView):
    """
    Vista para listar las clases.
    """

    model = Clase
    queryset = Clase.objects.filter(
        fecha_clase__gte=timezone.now() + timezone.timedelta(hours=4)
    ).order_by("fecha_clase")
    form_class = BuscarClaseForm
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_filtros = self.form_class(self.request.GET or None)
        context["form_filtros"] = form_filtros
        context["clases_antiguas"] = Clase.objects.filter(
            fecha_clase__lt=timezone.now()
        ).order_by("fecha_clase")
        form_general = BuscarClaseGeneralForm(self.request.GET or None)
        if form_general.is_valid():
            tipo_clase_general = form_general.cleaned_data["tipo_clase"]
            if tipo_clase_general:
                context["clases_buscadas"] = Clase.objects.filter(
                    tipo_clase__nombre__icontains=tipo_clase_general
                )
                if not context["clases_buscadas"]:
                    messages.warning(self.request, "No se encontraron clases")

        return context

    def get_queryset(self):

        form_filtros = self.form_class(self.request.GET or None)
        if form_filtros.is_valid():
            tramo = form_filtros.cleaned_data["tramo"]
            tipo_clase = form_filtros.cleaned_data["tipo_clase"]
            fecha_clase = form_filtros.cleaned_data["fecha_clase"]
            if tramo:
                self.queryset = self.queryset.filter(tramo=tramo)
            if tipo_clase:
                self.queryset = self.queryset.filter(tipo_clase__nombre=tipo_clase)
            if fecha_clase:
                self.queryset = self.queryset.filter(fecha_clase=fecha_clase)

        return super().get_queryset()


class EditarClase(UpdateView):
    """
    Vista para editar una clase.
    """

    model = Clase
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("listar_clases")
    form_class = CrearClaseForm


class EliminarClase(DeleteView):
    """
    Vista para eliminar una clase.
    """

    model = Clase
    success_url = reverse_lazy("listar_clases")


class DetalleClase(DetailView):
    """
    Vista para ver los detalles de una clase.
    """

    model = Clase


# endregion
# region Clases Adicionales


class TopTenClases(ListView):
    """
    Vista para listar las clases por tipo,tramo o fecha.
    """

    model = Clase
    template_name_suffix = "_top_ten"
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clases = (
            Clase.objects.annotate(num_reservas=Count("reserva"))
            .filter(fecha_clase__gte=timezone.now() - timezone.timedelta(days=7))
            .order_by("-num_reservas")[:10]
        )
        context["clases_top_ten"] = clases

        return context


# endregion


# region CRUD de Reservas
class CrearReserva(View):
    """
    Vista para crear una reserva.
    """

    def get(self, request: HttpRequest, pk) -> HttpResponse:
        """
        Método get para obtener una reserva.
        """
        clase = get_object_or_404(Clase, pk=pk)
        if clase.cupos_disponibles == 0:
            messages.warning(request, "No hay cupos disponibles")
            return redirect("listar_clases")
        if Reserva.objects.filter(clase__valido=True, usuario=request.user).exists():
            messages.warning(request, "Ya existe una reserva para este usuario")
            return redirect("listar_clases")
        form_general = BuscarClaseGeneralForm()
        return render(
            request,
            "clases/reserva_form.html",
            {"clase": clase, "form_general": form_general},
        )

    def post(self, request: HttpRequest, pk) -> HttpResponse:
        """
        Método post para crear una reserva.
        """
        clase = get_object_or_404(Clase, pk=pk)
        usuario = request.user
        reserva = Reserva.objects.create(
            clase=clase,
            usuario=usuario,
            estado="Realizada",
            nombre_clase=clase.tipo_clase.nombre,
        )
        clase.valido = True
        clase.cupos_disponibles -= 1
        clase.save()
        messages.success(request, "Reserva realizada")
        return redirect("detalle_reserva", pk=reserva.pk)


class ListarReservas(ListView):
    """
    Vista para listar las reservas.
    """

    model = Reserva
    queryset = Reserva.objects.all()
    form_class = BuscarReservaPorClienteForm
    paginate_by = 2

    def get_queryset(self):
        form = self.form_class(self.request.GET or None)
        if form.is_valid():
            usuario = form.cleaned_data["usuario"]
            clase = form.cleaned_data["clase"]
            if usuario:
                self.queryset = self.queryset.filter(usuario=usuario)
            if clase:
                self.queryset = self.queryset.filter(clase=clase)
        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_filtros"] = self.form_class(self.request.GET or None)
        return context


class EditarReserva(UpdateView):
    """
    Vista para editar una reserva.
    """

    model = Reserva
    form_class = CrearReservaStaffForm
    template_name_suffix = "_update_form"
    success_url = reverse_lazy("listar_reservas")


class EliminarReserva(DeleteView):
    """
    Vista para eliminar una reserva.
    """

    model = Reserva
    success_url = reverse_lazy("listar_reservas")


class DetalleReserva(DetailView):
    """
    Vista para ver los detalles de una reserva.
    """

    model = Reserva


class CancelarReserva(View):
    """
    Vista para cancelar una reserva.
    """

    def get(self, request, pk) -> HttpResponse:
        """
        Método get para obtener una reserva.
        """
        reserva = get_object_or_404(Reserva, pk=pk)
        return render(
            request, "clases/reserva_confirm_cancel.html", {"reserva": reserva}
        )

    def post(self, request, pk=None, *args, **kwargs) -> HttpResponse:
        """
        Método para cancelar una reserva.
        """
        pk = self.kwargs.get("pk")
        reserva = get_object_or_404(Reserva, pk=pk)
        reserva.estado = "Cancelada"

        if reserva.clase.fecha_clase and reserva.clase.fecha_clase < timezone.now():
            reserva.clase.cupos_disponibles += 1
        reserva.cancelar()
        messages.success(request, "Reserva cancelada")
        if request.user.is_staff:
            return redirect("listar_reservas")
        return redirect("reservas_cliente", request.user.username, request.user.pk)


# endregion
# region Reservas Adicionales
class CrearReservaStaff(View):
    """
    Vista para crear una reserva por el staff.
    """

    def get(self, request, pk):
        """
        Método get para obtener una reserva.
        """
        clase = get_object_or_404(Clase, pk=pk)
        form = CrearReservaStaffForm(initial={"clase": clase})
        return render(request, "clases/reserva_form_staff.html", {"form": form})

    def post(self, request, pk):
        """
        Método post para crear una reserva.
        """
        form = CrearReservaStaffForm(request.POST)
        if form.is_valid():
            clase = get_object_or_404(Clase, pk=pk)
            usuario = form.cleaned_data["usuario"]
            estado = form.cleaned_data["estado"]
            if clase.cupos_disponibles == 0:
                messages.warning(request, "No hay cupos disponibles")
                return redirect("listar_clases")
            if Reserva.objects.filter(clase=clase, usuario=usuario).exists():
                messages.warning(request, "Ya existe una reserva para este usuario")
                return redirect("listar_clases")
            reserva = Reserva.objects.create(
                clase=clase, usuario=usuario, estado=estado
            )
            reserva.save()
            return redirect("listar_reservas")
        return render(request, "clases/reserva_form_staff.html", {"form": form})


class ListarReservasClientes(ListView):
    """
    Vista para listar las clases para los clientes.
    """

    model = Reserva
    template_name_suffix = "_cliente_list"
    form_class = BuscarReservaParaClientesForm
    queryset = None
    paginate_by = 2

    def get_queryset(self):
        self.queryset = Reserva.objects.filter(
            usuario=self.request.user,
            estado="Realizada",
            clase__valido=True,
            clase__fecha_clase=timezone.now(),
        )
        form = self.form_class(self.request.GET or None)
        if form.is_valid():
            fecha = form.cleaned_data["fecha_reserva"]

clases/templates/clases/base.html
{% extends 'core/base.html' %} {% load static %} {% block title%}{%endblock%}

{%block navbar %}
<li class="nav-item">
  <a class="nav-link" aria-current="page" href="{%url 'clases_welcome'%}"
    >Inicio Clases</a
  >
</li>
<li class="nav-item">
  <a class="nav-link" aria-current="page" href="{%url 'listar_clases'%}"
    >Lista Clases</a
  >
</li>
{% if request.user.is_staff or request.is_superuser %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'usuarios_welcome' %}">Usuarios</a>
</li>
{% endif %}
{% if request.user.cliente %}
  <a class="nav-link" href="{% url 'reservas_cliente' request.user.username request.user.pk %}">Reservas</a>
{% elif request.user.is_staff or request.user.is_superuser %}
  <a class="nav-link" href="{% url 'listar_reservas' %}">Reservas</a>
{% endif %}


{% endblock %} 

clases/templates/clases/clase_buscar.html
{% extends "clases/index.html" %}{% load static %}{%block title%}Búsqueda clase{%endblock %}

{%block body %}
<form method="get">
  {% csrf_token %} {{ form_filtros.as_p }}
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
</form>
<h1 class="text-center">Clases encontradas</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre de la clase</th>
      <th>Duración</th>
      <th>Instructor</th>
      <th>Cupos disponibles</th>
      <th>Fecha</th>
      <th>Imagen</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    {%for clase in clase_list %}
    <tr>
      <td>{{clase.tipo_clase.nombre}}</td>
      <td>{{clase.tramo}} Minutos</td>
      <td>{{clase.instructor}}</td>
      <td>{{clase.cupos_disponibles}}</td>
      <td>{{clase.fecha_clase}}</td>
      <td>
        {%if clase.imagen%}
        <img src="{{clase.imagen.url}}" alt="Imagen de la clase" class="img-fluid mb-3" />
        {%endif%}
      </td>
      <td>
        <a class="btn btn-success" href="{%url 'detalle_clase' clase.pk %}">Detalle clase</a>
        {%if request.user.is_staff and request.is_superuser%}
        <a class="btn btn-warning" href="{% url 'editar_clase' clase.pk %}">Editar clase</a>
        <a class="btn btn-danger" href="{% url 'eliminar_clase' clase.pk %}">Eliminar clase</a>
        {%endif%}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%if messages%} {%for message in messages%}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%} {%endif%}
<!-- Pagination -->
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="{% url 'listar_clases'%}?page={{ page_obj.previous_page_number }}">Página anterior</a>
    {% endif %}

    <span class="current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
      <a href="{% url 'listar_clases'%}?page={{ page_obj.next_page_number }}" class="text-black">Siguiente</a>
      <a href="{% url 'listar_clases'%}?page={{ page_obj.paginator.num_pages }}"class="text-black">Ultima &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock %}

clases/templates/clases/clase_detail.html
{% extends 'clases/index.html'%} {% load static %}{%block title%}Detalle
clase{%endblock %} {%block body%}

<h1 class="text-center">Detalle de la clase {{clase.tipo_clase}}</h1>
<div class="row shadow-lg py-5 my-5 bg-white text-black">
  <div class="col-12">

    <h3>Duración</h3>
    <p>{{clase.tramo}} Minutos</p>
    <h3>Instructor </h3>
    <p>{{clase.instructor}}</p>
    <h3>Cupos disponibles </h3>
    <p>{{clase.cupos_disponibles}}</p>
    <h3>Fecha </h3>
      <p>{{clase.fecha_clase}}</p>
    <!--Imagen-->
    {%if clase.imagen%}
    <img
      src="{{clase.imagen.url}}"
      alt="Imagen de la clase"
      class="img-fluid mb-3"
    />
    {%endif%} 
    </br>
    {% if request.user.is_authenticated and request.user.cliente%}
    <a class="btn btn-success" href="{% url 'reservar_clase' clase.pk %}"
      >Reservar clase</a
    >
    {% endif %} {%if request.user.is_staff and request.user.is_superuser%}
    <a class="btn btn-success" href="{%url 'reservar_clase_staff' clase.pk %}"
      >Reservar clase
    </a>
    <a class="btn btn-warning" href="{% url 'editar_clase' clase.pk %}">
      Editar clase
    </a>
    <a class="btn btn-danger" href="{% url 'eliminar_clase' clase.pk %}">
      Eliminar clase
    </a>
    {%endif%} {%if messages%} {%for message in messages%}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%} {%endif%}
  </div>
</div>

{%endblock %}

clases/templates/clases/clase_form.html
{% extends 'clases/index.html'%}{% load static %}{%block title%}Nueva
clase{%endblock%} {%block body%}

<h1 class="text-center">Nueva clase</h1>
<form
  action="{% url 'crear_clase'%}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary" value="Guardar">
    <i class="bi bi-save"> </i>Guardar
  </button>
</form>
{%if messages%} {%for message in messages%}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%} {%endif%}
{%endblock %}

clases/templates/clases/clase_list.html
{% extends 'clases/index.html'%}{% load static %} {%block title%}Listado de
clases{%endblock%} {%block body%}
<form class="form-inline my-2 my-lg-0" method="get" role="search">
  {{form_filtros.as_p}}
  <button class="btn btn-success my-2 my-sm-0" type="submit">
    Buscar
  </button>
</form>
{%if messages%} {%for message in messages%}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%} {%endif%}
{%if clases_buscadas%}
<h1 class="text-center">Clases encontradas</h1>
{%for clase in clases_buscadas%}
<div class="row shadow-lg py-5 my-3 clase bg-white text-black rounded">
  <div class="col-8">
   
    <h2>{{clase.tipo_clase.nombre}}</h2>
    <p>Cupos disponibles {{clase.cupos_disponibles}}</p>
    <p>Fecha  {{clase.fecha_clase}}</p>
    <a class="btn btn-success" href="{%url 'detalle_clase' clase.pk %}">
      Detalle clase
    </a>
    {%if request.user.is_staff and request.is_superuser%}
    <a class="btn btn-warning" href="{% url 'editar_clase' clase.pk %}">
      Editar clase
    </a>
    <a class="btn btn-danger" href="{% url 'eliminar_clase' clase.pk %}">
      Eliminar clase
    </a>
    {%endif%}
  </div>
  <div class="col-4">
   {%if clase.imagen%}
    <img src="{{clase.imagen.url}}" class="img-fluid" alt="Imagen de la clase">
    {%endif%}
  </div>
</div>
{%endfor%} {%endif%} 
{%if not clases_buscadas%}
<h1 class="text-center">Listado de clases</h1>
{%for clase in clase_list %}
<div class="row shadow-lg py-5 my-3 clase bg-white text-black rounded">
  <div class="col-8">
   
    <h2>{{clase.tipo_clase.nombre}}</h2>
    <p>Cupos disponibles {{clase.cupos_disponibles}}</p>
    <p>Fecha  {{clase.fecha_clase}}</p>
    <a class="btn btn-success" href="{%url 'detalle_clase' clase.pk %}">
      Detalle clase
    </a>
    {%if request.user.is_staff and request.is_superuser%}
    <a class="btn btn-warning" href="{% url 'editar_clase' clase.pk %}">
      Editar clase
    </a>
    <a class="btn btn-danger" href="{% url 'eliminar_clase' clase.pk %}">
      Eliminar clase
    </a>
    {%endif%}
  </div>
  <div class="col-4">
    {%if clase.imagen%}
    <img src="{{clase.imagen.url}}" class="img-fluid" alt="Imagen de la clase">
    {%endif%}
  </div>
</div>
{%endfor%} 
{%if request.user.is_superuser or request.user.is_staff%}
<h1 class="text-center">Clases antiguas</h1>
{%for clase in clases_antiguas%}
<div class="row shadow-lg py-5 my-3 clase bg-white text-black rounded">
  <div class="col-8">
   
    <h2>{{clase.tipo_clase.nombre}}</h2>
    <p>Cupos disponibles {{clase.cupos_disponibles}}</p>
    <p>Fecha  {{clase.fecha_clase}}</p>
    <a class="btn btn-success" href="{%url 'detalle_clase' clase.pk %}">
      Detalle clase
    </a>
    <a class="btn btn-warning" href="{% url 'editar_clase' clase.pk %}">
      Editar clase
    </a>
    <a class="btn btn-danger" href="{% url 'eliminar_clase' clase.pk %}">
      Eliminar clase
    </a>
  </div>
  <div class="col-4">
    {%if clase.imagen%}
    <img src="{{clase.imagen.url}}" class="img-fluid" alt="Imagen de la clase">
    {%endif%}
  </div>
</div>
{%endfor%}
{%endif%}
{%endif%}
<!-- Pagination -->
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="{% url 'listar_clases'%}?page={{ page_obj.previous_page_number }}">Página anterior</a>
    {% endif %}
    <span class="current-page">{{ page_obj.number }}</span>
    {% if page_obj.has_next %}
      <a href="{% url 'listar_clases'%}?page={{ page_obj.next_page_number }}" class="text-black">Siguiente</a>
      <a href="{% url 'listar_clases'%}?page={{ page_obj.paginator.num_pages }}"class="text-black">Ultima &raquo;</a>
    {% endif %}
  </span>
</div>
{%endblock%}

clases/templates/clases/reserva_cliente_list.html
{% extends 'clases/base.html'%}{%block title%}Lista Reservas Cliente{%endblock %}
{%block body%}
<form class="form-inline my-2 my-lg-0" method="get" action"{% url 'reservas_cliente' request.user.username request.user.pk%}">
  {{form.as_p}}
  <button class="btn btn-success my-2 my-sm-0" type="submit">
    Buscar
  </button>
</form>
{%if messages%} {%for message in messages%}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {%endfor%} {%endif%}
<h1>Clases de {{request.user}}</h1>
{%for reserva in reserva_list %}
<div class="row shadow-lg bg-white clase py-5 my-3 rounded text-black">
  <div class="col-12">
    <h2>{{reserva.clase.tipo_clase.nombre}}</h2>
    <h3>Duración: </h3>
    <p>{{reserva.clase.tramo}} minutos</p>
    <h3>Instructor: </h3>
    <p>{{reserva.clase.instructor}}</p>
<p>Estado: {{reserva.estado}}</p>
    
    <h3>Fecha: </h3>
    <p>{{reserva.clase.fecha_clase}}</p>
    <a class="btn btn-success" href="{%url 'detalle_reserva' reserva.pk %}"
      >Detalle Reserva
    </a>
  </div>
</div>
  {% endfor %} 
  <!-- Pagination -->
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      
      <a href="{% url 'listar_clases'%}?page={{ page_obj.previous_page_number }}">Página anterior</a>
    {% endif %}

    <span class="current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
      <a href="{% url 'listar_clases'%}?page={{ page_obj.next_page_number }}" class="text-black">Siguiente</a>
      <a href="{% url 'listar_clases'%}?page={{ page_obj.paginator.num_pages }}"class="text-black">Ultima &raquo;</a>
    {% endif %}
  </span>
</div>{% endblock %}